package com.abraham.prueba7.data;
// Generated 29-dic-2016 12:33:52 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ejerce generated by hbm2java
 */
@Entity
@Table(name = "ejerce", schema = "public")
public class Ejerce implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idejerce;
	private Perfil perfil;
	private Usuario usuario;

	public Ejerce() {
	}

	public Ejerce(int idejerce) {
		this.idejerce = idejerce;
	}

	public Ejerce(int idejerce, Perfil perfil, Usuario usuario) {
		this.idejerce = idejerce;
		this.perfil = perfil;
		this.usuario = usuario;
	}

	@Id

	@Column(name = "idejerce", unique = true, nullable = false)
	public int getIdejerce() {
		return this.idejerce;
	}

	public void setIdejerce(int idejerce) {
		this.idejerce = idejerce;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idperfil")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iduser")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
