package com.abraham.prueba7.data;
// Generated 29-dic-2016 12:33:52 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name = "pago", schema = "public")
public class Pago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idpago;
	private Calendariopagos calendariopagos;
	private Involucrado involucrado;
	private Date fpago;

	public Pago() {
	}

	public Pago(int idpago) {
		this.idpago = idpago;
	}

	public Pago(int idpago, Calendariopagos calendariopagos, Involucrado involucrado, Date fpago) {
		this.idpago = idpago;
		this.calendariopagos = calendariopagos;
		this.involucrado = involucrado;
		this.fpago = fpago;
	}

	@Id

	@Column(name = "idpago", unique = true, nullable = false)
	public int getIdpago() {
		return this.idpago;
	}

	public void setIdpago(int idpago) {
		this.idpago = idpago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcp")
	public Calendariopagos getCalendariopagos() {
		return this.calendariopagos;
	}

	public void setCalendariopagos(Calendariopagos calendariopagos) {
		this.calendariopagos = calendariopagos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idit")
	public Involucrado getInvolucrado() {
		return this.involucrado;
	}

	public void setInvolucrado(Involucrado involucrado) {
		this.involucrado = involucrado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fpago", length = 13)
	public Date getFpago() {
		return this.fpago;
	}

	public void setFpago(Date fpago) {
		this.fpago = fpago;
	}

}
